import { Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { ReactNode } from "react";
import { color, font, page } from "@/lib/pdf/theme";
import { Clause, ClauseHeading, DraftWatermark, PageFooter, PageHeader, SubClause } from "@/lib/pdf/components";
import { formatCurrency, formatDate } from "@/lib/mockData";
import { numberToWords, policy } from "@/lib/pdf/policy";
import type { ProposalPdfData } from "@/lib/pdf/data";

const styles = StyleSheet.create({
  page: {
    fontFamily: font.family,
    padding: page.marginPt,
    paddingTop: 70,
    paddingBottom: 50,
    fontSize: font.body,
    color: color.body,
  },
  partTitle: { fontSize: 20, fontWeight: 700, color: color.ink, marginBottom: 4 },
  partSubtitle: { fontSize: 10, color: color.body, marginBottom: 12 },
  definitionsTable: { marginTop: 4, marginBottom: 8 },
  definitionRow: { flexDirection: "row", marginBottom: 6 },
  definitionTerm: { width: "26%", fontSize: font.body, fontWeight: 700, color: color.ink },
  definitionBody: { width: "74%", fontSize: font.body, color: color.body, lineHeight: 1.5 },
  execBlock: { marginTop: 16, borderTop: "0.5px solid " + color.rule, paddingTop: 12 },
  execRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 24 },
  execCol: { width: "46%" },
  execLine: { borderBottom: "0.5px solid " + color.ink, marginTop: 26, marginBottom: 4, height: 1 },
  execLabel: { fontSize: 8, color: color.body },
  noticeBox: {
    marginTop: 8,
    marginBottom: 8,
    border: "0.5px solid " + color.rule,
    backgroundColor: color.tableHead,
    padding: 10,
  },
});

function Definition({ term, children }: { term: string; children: ReactNode }) {
  return (
    <View style={styles.definitionRow} wrap={false}>
      <Text style={styles.definitionTerm}>{term}</Text>
      <Text style={styles.definitionBody}>{children}</Text>
    </View>
  );
}

export function PartB({ data, showWatermark }: { data: ProposalPdfData; showWatermark: boolean }) {
  const d = data;

  return (
    <Page size={page.size} style={styles.page} wrap>
      <PageHeader title="SOLAR SUPPLY AGREEMENT" reference={d.reference} />
      <DraftWatermark show={showWatermark} />

      <Text style={styles.partTitle}>Part B — Draft Agreement Terms</Text>
      <Text style={styles.partSubtitle}>
        Reference {d.reference} — {d.propertyAddress}
      </Text>

      <ClauseHeading number="1">Parties</ClauseHeading>
      <Clause number="1.1">
        This Agreement is between {d.ownerName} of {d.propertyAddress} (&quot;the Owner&quot;) and{" "}
        {d.occupantName} of {d.propertyAddress} (&quot;the Occupant&quot;).
      </Clause>
      <Clause number="1.2">
        It relates to the solar energy system installed at {d.propertyAddress} (&quot;the
        Property&quot;).
      </Clause>

      <ClauseHeading number="2">Definitions</ClauseHeading>
      <View style={styles.definitionsTable}>
        <Definition term="Solar Energy">
          Electricity generated by the solar system at the Property and consumed at the Property.
        </Definition>
        <Definition term="Tariff Rate">
          The rate of {d.tariffRateCents} cents per kilowatt hour charged to the Occupant for Solar
          Energy, subject to clause 6.
        </Definition>
        <Definition term="Recovery Balance">
          The amount defined in clause 7, currently {formatCurrency(d.recoveryBalance)}.
        </Definition>
        <Definition term="Reserve">
          The maintenance reserve funded under clause 8.
        </Definition>
        <Definition term="Grid Rate">
          The rate the Occupant&apos;s electricity retailer would otherwise charge for the same energy,
          currently {d.gridRateCents} cents per kilowatt hour.
        </Definition>
        <Definition term="Billing Period">The period covered by each Statement.</Definition>
        <Definition term="Statement">
          The record of metered data and charges issued to both parties each Billing Period.
        </Definition>
        <Definition term="Completion">The date the Recovery Balance reaches zero.</Definition>
        <Definition term="Platform">
          The SunShare web portal through which both parties view metered data and the Recovery
          Balance.
        </Definition>
      </View>

      <ClauseHeading number="3">Term</ClauseHeading>
      <Clause number="3.1">
        This Agreement commences on {d.startDateLabel} and continues until the earlier of:
      </Clause>
      <SubClause letter="a">Completion;</SubClause>
      <SubClause letter="b">
        {d.endDateLabel}, being {d.termYears} years from commencement; or
      </SubClause>
      <SubClause letter="c">termination under clause 12 or 13.</SubClause>
      <Clause number="3.2">
        The maximum term of this Agreement is {numberToWords(policy.maxTermYears)} (
        {policy.maxTermYears}) years. This limit exists so that the Agreement remains within the
        class exemption available for residential power purchase agreements.
      </Clause>
      <Clause number="3.3">
        If the Recovery Balance is not extinguished by the end of the term, the shortfall is borne
        by the Owner and no further amount is payable by the Occupant or any subsequent occupant.
      </Clause>

      <ClauseHeading number="4">Supply</ClauseHeading>
      <Clause number="4.1">
        The Owner will make Solar Energy generated at the Property available to the Occupant.
      </Clause>
      <Clause number="4.2">
        This Agreement supplements, and does not replace, the Occupant&apos;s electricity supply.
        The Occupant retains their own retail electricity account and remains free to choose their
        retailer at any time.
      </Clause>
      <Clause number="4.3">
        The Owner will not require the Occupant to purchase any electricity other than Solar
        Energy generated at the Property.
      </Clause>

      <ClauseHeading number="5">Charges</ClauseHeading>
      <Clause number="5.1">
        The Occupant will pay the Owner the Tariff Rate of {d.tariffRateCents} cents per kilowatt
        hour for Solar Energy consumed at the Property.
      </Clause>
      <Clause number="5.2">
        The Tariff Rate is fixed for the duration of the Occupant&apos;s tenancy and is reviewed
        only on a change of occupant under clause 11.
      </Clause>
      <Clause number="5.3">
        Charges are calculated per Billing Period from metered data and set out in a Statement
        issued to both parties.
      </Clause>
      <Clause number="5.4">The Occupant is not charged for Solar Energy exported to the grid.</Clause>

      <ClauseHeading number="6">Never-Worse-Off Guarantee</ClauseHeading>
      <Clause number="6.1">
        In any half-hour interval, the amount charged for Solar Energy will not exceed what the
        Occupant would have paid their retailer for the same energy in that interval.
      </Clause>
      <Clause number="6.2">
        Where the Occupant&apos;s retail tariff provides energy at zero or reduced cost in an
        interval — including any free-period offer — the Tariff Rate for that interval is reduced
        accordingly, to zero if applicable.
      </Clause>
      <Clause number="6.3">
        The Occupant is not required to monitor or elect anything for clause 6.1 to apply. It is
        applied automatically.
      </Clause>

      <ClauseHeading number="7">Recovery Balance</ClauseHeading>
      <Clause number="7.1">
        The Recovery Balance at commencement is {formatCurrency(d.recoveryBalance)}, comprising
        the net installed cost, the funded Reserve, and the agreed return set out in Schedule 2.
      </Clause>
      <Clause number="7.2">
        The Recovery Balance attaches to the Property and not to any Occupant. No Occupant is
        personally liable for it.
      </Clause>
      <Clause number="7.3">The Recovery Balance is reduced by:</Clause>
      <SubClause letter="a">charges paid under clause 5; and</SubClause>
      <SubClause letter="b">revenue received by the Owner for Solar Energy exported to the grid.</SubClause>
      <Clause number="7.4">
        Amounts contributed by an Occupant permanently reduce the Recovery Balance and are not
        reinstated on a change of occupant.
      </Clause>
      <Clause number="7.5">
        The current Recovery Balance is visible to both parties at all times through the Platform.
      </Clause>

      <ClauseHeading number="8">Maintenance Reserve</ClauseHeading>
      <Clause number="8.1">
        {formatCurrency(d.monthlyReserveContribution)} per Billing Period is credited to the
        Reserve.
      </Clause>
      <Clause number="8.2">
        The Reserve is applied solely to maintenance, repair and replacement of the system, and is
        held for the benefit of the Property.
      </Clause>
      <Clause number="8.3">
        On sale of the Property, the Reserve balance transfers with the Property and must be
        disclosed to the purchaser.
      </Clause>

      <ClauseHeading number="9">Owner obligations</ClauseHeading>
      <Clause number="9.1">
        The Owner will maintain the system in good working order and effect repairs within a
        reasonable period.
      </Clause>
      <Clause number="9.2">The Owner will maintain insurance covering the system.</Clause>
      <Clause number="9.3">
        The Owner will provide the Occupant with metered generation and consumption data through
        the Platform.
      </Clause>
      <Clause number="9.4">
        The Owner will not increase rent by reason of this Agreement, and the charges under this
        Agreement are separate from and additional to no rent adjustment.
      </Clause>

      <ClauseHeading number="10">Performance suspension</ClauseHeading>
      <Clause number="10.1">
        Where generation falls below {policy.performanceSuspensionThresholdPercent}% of expected
        output for {policy.performanceSuspensionDays} consecutive days, charges under clause 5 are
        automatically suspended.
      </Clause>
      <Clause number="10.2">
        Suspension continues until output is restored. No charges accrue during suspension.
      </Clause>
      <Clause number="10.3">
        The Occupant is not required to give notice for clause 10.1 to operate.
      </Clause>

      <ClauseHeading number="11">Change of occupant</ClauseHeading>
      <Clause number="11.1">
        On a change of occupant, the Recovery Balance continues unchanged and attaches to the
        Property.
      </Clause>
      <Clause number="11.2">
        A new Tariff Rate is determined for the incoming occupant based on their circumstances,
        subject always to clause 6.
      </Clause>
      <Clause number="11.3">
        The incoming occupant must be given this Agreement and the current Recovery Balance in
        writing before entering into it.
      </Clause>

      <ClauseHeading number="12">Termination by the Occupant</ClauseHeading>
      <Clause number="12.1">
        The Occupant may terminate this Agreement at any time by giving{" "}
        {policy.occupantTerminationNoticeDays} days&apos; written notice, without penalty and
        without giving reasons.
      </Clause>
      <Clause number="12.2">
        On termination, the Occupant owes nothing beyond charges already incurred, and no amount
        of the Recovery Balance is payable by them.
      </Clause>
      <Clause number="12.3">
        Termination of this Agreement does not affect the Occupant&apos;s residential tenancy.
      </Clause>

      <ClauseHeading number="13">Termination by the Owner</ClauseHeading>
      <Clause number="13.1">
        The Owner may terminate only for non-payment persisting more than{" "}
        {policy.ownerTerminationNonPaymentDays} days after written notice, or where the system is
        permanently removed.
      </Clause>
      <Clause number="13.2">
        The Owner may not terminate to re-let the Property at a higher Tariff Rate.
      </Clause>

      <ClauseHeading number="14">Completion</ClauseHeading>
      <Clause number="14.1">
        On the Recovery Balance reaching zero, charges under clause 5 cease permanently.
      </Clause>
      <Clause number="14.2">
        After Completion, Solar Energy is supplied to the Occupant at no charge for the remaining
        life of the system.
      </Clause>
      <Clause number="14.3">The Owner remains responsible for maintenance after Completion.</Clause>
      <Clause number="14.4">
        Completion cannot be reversed, and no new Recovery Balance may be created except for a
        capital replacement agreed in writing under a separate agreement complying with clause 3.2.
      </Clause>

      <ClauseHeading number="15">Rebates and concessions</ClauseHeading>
      <Clause number="15.1">
        Nothing in this Agreement affects the Occupant&apos;s eligibility for any government energy
        rebate or concession.
      </Clause>
      <Clause number="15.2">
        The Occupant retains their own retail electricity account, which is a condition of
        eligibility for such rebates.
      </Clause>

      <ClauseHeading number="16">Metering and data</ClauseHeading>
      <Clause number="16.1">Charges are based on metered data recorded at the Property.</Clause>
      <Clause number="16.2">Either party may request the underlying interval data at any time.</Clause>
      <Clause number="16.3">
        Personal information is handled in accordance with the Privacy Act 1988 (Cth).
      </Clause>

      <ClauseHeading number="17">Disputes</ClauseHeading>
      <Clause number="17.1">Parties will first attempt to resolve disputes directly.</Clause>
      <Clause number="17.2">
        Unresolved disputes may be referred to the {policy.ombudsman}.
      </Clause>
      <Clause number="17.3">Charges in dispute are suspended pending resolution.</Clause>

      <ClauseHeading number="18">Regulatory</ClauseHeading>
      <Clause number="18.1">
        The Owner is responsible for holding any authorisation or exemption required to sell
        energy under the National Energy Retail Law.
      </Clause>
      <Clause number="18.2">
        This Agreement is drafted to fall within the conditions applying to residential power
        purchase agreements, including a term of less than ten years and an unrestricted right of
        early termination.
      </Clause>
      <Clause number="18.3">Written in plain language as required of exempt sellers.</Clause>

      <ClauseHeading number="19">General</ClauseHeading>
      <Clause number="19.1">
        This Agreement is governed by the law of New South Wales.
      </Clause>
      <Clause number="19.2">
        This Agreement is the entire agreement between the parties as to its subject matter.
      </Clause>
      <Clause number="19.3">Variations must be in writing and signed by both parties.</Clause>
      <Clause number="19.4">
        If any provision of this Agreement is invalid or unenforceable, the remaining provisions
        continue in full force.
      </Clause>
      <Clause number="19.5">
        Notices under this Agreement may be given through the Platform or in writing to the address
        recorded for each party.
      </Clause>

      <ClauseHeading number="20">Execution</ClauseHeading>
      <View style={styles.noticeBox}>
        <Text>
          By signing, each party confirms they have read this Agreement, have had the opportunity
          to obtain independent advice, and enter into it freely.
        </Text>
      </View>

      <View style={styles.execBlock} wrap={false}>
        <View style={styles.execRow}>
          <View style={styles.execCol}>
            <Text style={styles.execLabel}>Owner</Text>
            <Text style={{ marginTop: 10 }}>{d.ownerName}</Text>
            <View style={styles.execLine} />
            <Text style={styles.execLabel}>Signature</Text>
            <View style={styles.execLine} />
            <Text style={styles.execLabel}>Date</Text>
          </View>
          <View style={styles.execCol}>
            <Text style={styles.execLabel}>Occupant</Text>
            <Text style={{ marginTop: 10 }}>{d.occupantName}</Text>
            <View style={styles.execLine} />
            <Text style={styles.execLabel}>Signature</Text>
            <View style={styles.execLine} />
            <Text style={styles.execLabel}>Date</Text>
          </View>
        </View>
        <View style={styles.execRow}>
          <View style={styles.execCol}>
            <Text style={styles.execLabel}>Witness</Text>
            <View style={styles.execLine} />
            <Text style={styles.execLabel}>Name</Text>
            <View style={styles.execLine} />
            <Text style={styles.execLabel}>Signature</Text>
            <View style={styles.execLine} />
            <Text style={styles.execLabel}>Date</Text>
          </View>
        </View>
      </View>

      <PageFooter generatedLabel={`Generated ${formatDate(d.preparedDate.toISOString())}`} />
    </Page>
  );
}
